# ==============================================================================
# 02.2 REPRODUCE XU ET AL. FIGURE 1C/1E-STYLE OUTPUTS
# ==============================================================================
# Purpose: reproduce published marker and stage patterns. Run from the repository root after scripts 02 and 02.1.
# Stage assignments: Xu et al., Supplementary Table S1 (patient information).

suppressPackageStartupMessages({
  library(Seurat)
  library(ggplot2)
})

set.seed(42)
dir.create("figures", recursive = TRUE, showWarnings = FALSE)
dir.create("results", recursive = TRUE, showWarnings = FALSE)

save_png <- function(plot, filename, width, height) {
  # Draw outside the synced project folder and copy the finished PNG into it.
  tmp <- tempfile(fileext = ".png")
  on.exit(unlink(tmp), add = TRUE)
  ggplot2::ggsave(tmp, plot = plot, width = width, height = height,
                  dpi = 300, bg = "white", device = grDevices::png)
  if (!file.copy(tmp, filename, overwrite = TRUE)) {
    stop("Could not update ", filename,
         ". Close the image if open and check whether OneDrive is syncing it.")
  }
}

stage_by_sample <- c(
  Norm1 = "Nonmalignant", Norm2 = "Nonmalignant", Norm3 = "Nonmalignant",
  Norm4 = "Nonmalignant", Norm5 = "Nonmalignant",
  Cancer1 = "Advanced", Cancer2 = "Advanced", Cancer3 = "Early",
  Cancer4 = "Early", Cancer5 = "Advanced", Cancer6 = "Advanced",
  Cancer7 = "Early"
)
stage_levels <- c("Nonmalignant", "Early", "Advanced")

# Xu et al. Fig. 1C marker panel, also used by script 02.
marker_panel <- list(
  "T cell" = c("CD3D", "CD3E", "CD8A", "CD4"),
  "Epithelia" = c("KRT18", "EPCAM", "CD24", "KRT19"),
  "Monocytic" = c("CD14", "C1QA"),
  "Endothelia" = c("VCAM1", "PECAM1", "CLDN5"),
  "Cell cycle cell" = c("MKI67", "TOP2A"),
  "Fibroblast" = c("DCN", "OGN"),
  "B cell_plasma" = c("CD79A", "JCHAIN"),
  "SMC_myoFibroblast" = c("ACTA2", "MYH11", "TAGLN")
)
original_colors <- c(
  "T cell" = "#E6B8D7", "Epithelia" = "#4DAF4A",
  "Fibroblast" = "#56B4E9", "Monocytic" = "#E69F00",
  "Endothelia" = "#F4A582", "Cell cycle cell" = "#C7D36F",
  "B cell_plasma" = "#355C7D", "SMC_myoFibroblast" = "#D55E5E"
)
# The refined UMAP was generated by DimPlot's eight-level default ggplot hue palette.
refined_colors <- c(
  "B cell_plasma" = "#F8766D", "Cell cycle cell" = "#CD9600",
  "Endothelia" = "#7CAE00", "Epithelia" = "#00BE67",
  "Fibroblast" = "#00BFC4", "Myeloid" = "#00A9FF",
  "SMC_myoFibroblast" = "#C77CFF", "T cell" = "#FF61CC"
)
# Different from the paper's stage palette; maintained across both versions.
stage_colors <- c("Nonmalignant" = "#0072B2", "Early" = "#E69F00",
                  "Advanced" = "#CC79A7")
# Identical comparison order and colours in both composition figures.
# Monocytic (Xu) and Myeloid (refined) occupy the same position.
composition_order <- c("T cell", "Epithelia", "Fibroblast", "Monocytic",
                       "Endothelia", "Cell cycle cell", "B cell_plasma",
                       "SMC_myoFibroblast")
composition_colors <- c(
  "T cell" = "#CC79A7", "Epithelia" = "#009E73",
  "Fibroblast" = "#56B4E9", "Monocytic" = "#D55E00",
  "Myeloid" = "#D55E00", "Endothelia" = "#0072B2",
  "Cell cycle cell" = "#E69F00", "B cell_plasma" = "#3B3B3B",
  "SMC_myoFibroblast" = "#F0E442"
)

# Require an exact sample token; never infer a stage from an unmatched name.
# Handles e.g. Norm1, Norm1_..., ..._Cancer3_..., with case-insensitive matching.
extract_sample <- function(x) {
  hits <- regmatches(x, gregexpr(
    "(?i)(?<![A-Za-z0-9])(?:Norm[1-5]|Cancer[1-7])(?![0-9])",
    x, perl = TRUE
  ))
  vapply(hits, function(z) {
    z <- unique(tolower(z))
    if (length(z) != 1L) return(NA_character_)
    key <- names(stage_by_sample)[match(z, tolower(names(stage_by_sample)))]
    if (length(key) != 1L || is.na(key)) NA_character_ else key
  }, character(1))
}

make_figures <- function(input_rds, prefix, annotation_col, colors) {
  if (!file.exists(input_rds)) stop("Required Seurat RDS missing: ", input_rds)
  obj <- readRDS(input_rds)
  required <- c("orig.ident", annotation_col)
  absent <- setdiff(required, colnames(obj[[]]))
  if (length(absent)) stop(input_rds, " lacks metadata: ", paste(absent, collapse = ", "))
  if (!("umap" %in% Reductions(obj))) stop(input_rds, " lacks a 'umap' reduction")
  DefaultAssay(obj) <- "RNA"
  labels <- as.character(obj[[annotation_col, drop = TRUE]])
  if (anyNA(labels) || any(!labels %in% names(colors))) {
    stop("Unmapped cell-type labels in ", input_rds, ": ",
         paste(unique(labels[is.na(labels) | !labels %in% names(colors)]), collapse = ", "))
  }
  sample_ids <- as.character(obj$orig.ident)
  mapped_samples <- extract_sample(sample_ids)
  if (anyNA(mapped_samples)) {
    stop("Cannot map these orig.ident values to Supplementary Table S1: ",
         paste(unique(sample_ids[is.na(mapped_samples)]), collapse = ", "),
         ". Provide the sample-name mapping before interpreting clinical stage.")
  }
  obj$clinical_stage_S1 <- factor(unname(stage_by_sample[mapped_samples]),
                                   levels = stage_levels)
  if (anyNA(obj$clinical_stage_S1)) stop("Missing clinical stage after mapping")
  write.csv(data.frame(orig.ident = sort(unique(sample_ids)),
                       sample_S1 = extract_sample(sort(unique(sample_ids))),
                       clinical_stage = unname(stage_by_sample[
                         extract_sample(sort(unique(sample_ids)))])),
            file.path("results", paste0(prefix, "_sample_stage_mapping.csv")),
            row.names = FALSE)

  # Fig. 1C: preserve the marker groups and show the relevant annotation.
  panel <- marker_panel
  if (annotation_col == "cell_type_refined") {
    names(panel)[names(panel) == "Monocytic"] <- "Myeloid"
  }
  features <- lapply(panel, intersect, y = rownames(obj))
  features <- features[lengths(features) > 0L]
  missing_genes <- setdiff(unlist(marker_panel), unlist(features))
  if (length(missing_genes)) warning(prefix, " missing marker genes: ",
                                     paste(missing_genes, collapse = ", "))
  if (!length(features)) stop("No Fig. 1C marker genes in ", input_rds)
  plot_order <- names(colors)[names(colors) %in% unique(labels)]
  obj$plot_cell_type_22 <- factor(labels, levels = plot_order)
  # Match the reference image's top-to-bottom lineage order.
  dot_top_to_bottom <- c("T cell", "SMC_myoFibroblast",
                         if (annotation_col == "cell_type_refined") "Myeloid" else "Monocytic",
                         "Fibroblast", "Epithelia", "Endothelia",
                         "Cell cycle cell", "B cell_plasma")
  dot_order <- rev(dot_top_to_bottom[dot_top_to_bottom %in% unique(labels)])
  obj$dot_cell_type_22 <- factor(labels, levels = dot_order)
  gene_order <- unique(unlist(features, use.names = FALSE))
  # Obtain Seurat's expression/detection summaries, then build an independent
  # ggplot. This guarantees a numeric, evenly spaced x axis without inheriting
  # DotPlot's discrete x scale or factor ordering.
  dot_data <- DotPlot(obj, features = gene_order,
                      group.by = "dot_cell_type_22", assay = "RNA")$data
  dot_data$x_gene <- match(as.character(dot_data$features.plot), gene_order)
  dot_data$lineage <- factor(as.character(dot_data$id), levels = dot_order)
  stopifnot(!anyNA(dot_data$x_gene), !anyNA(dot_data$lineage))
  if (annotation_col == "cell_type_refined") {
    stopifnot("Myeloid" %in% as.character(dot_data$lineage),
              !"Monocytic" %in% as.character(dot_data$lineage))
  }
  p_1c <- ggplot(dot_data, aes(x = x_gene, y = lineage)) +
    geom_point(aes(size = pct.exp, colour = avg.exp.scaled)) +
    scale_x_continuous(breaks = seq_along(gene_order), labels = gene_order,
                       limits = c(0.5, length(gene_order) + 0.5),
                       expand = c(0, 0)) +
    scale_colour_gradient(low = "#D3D3D3", high = "#2400FF",
                          name = "Average Expression") +
    scale_size_continuous(range = c(0.2, 6), limits = c(0, 100),
                          breaks = c(25, 50, 75), name = "Percent Expressed") +
    labs(title = "Dot plots of specific marker genes in each cell type",
         x = "Marker Genes", y = "Cell Lineage") +
    theme_classic() +
    theme(plot.title = element_text(face = "bold", size = 15),
          axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
          axis.text.y = element_text(size = 10))
  save_png(p_1c, file.path("figures", paste0(prefix, "_fig1C_continuous_marker_dotplot.png")),
           width = 13, height = 6)

  # Companion composition comparison: same top-to-bottom lineage order and
  # identical lineage colours for both annotations. This is a separate chart
  # from Xu et al.'s Fig. 1E, which is the stage-coloured UMAP below.
  composition_levels <- composition_order
  if (annotation_col == "cell_type_refined") {
    composition_levels[composition_levels == "Monocytic"] <- "Myeloid"
  }
  if (!setequal(unique(labels), composition_levels)) {
    stop(prefix, " cell-type labels differ from the shared composition order")
  }
  composition_type <- factor(labels, levels = composition_levels)
  composition_counts <- as.data.frame(table(
    stage = obj$clinical_stage_S1, cell_type = composition_type
  ))
  names(composition_counts)[3] <- "n_cells"
  stage_totals <- tapply(composition_counts$n_cells,
                         composition_counts$stage, sum)
  composition_counts$proportion <- composition_counts$n_cells /
    as.numeric(stage_totals[as.character(composition_counts$stage)])
  write.csv(composition_counts,
            file.path("results", paste0(prefix, "_matched_order_composition.csv")),
            row.names = FALSE)
  p_composition <- ggplot(composition_counts,
                          aes(x = stage, y = proportion, fill = cell_type)) +
    geom_col(width = 0.72, colour = "white", linewidth = 0.15) +
    scale_fill_manual(values = composition_colors,
                      breaks = composition_levels, limits = composition_levels,
                      drop = FALSE, name = "Cell type") +
    scale_y_continuous(labels = function(x) paste0(round(x * 100), "%"),
                       limits = c(0, 1), expand = c(0, 0)) +
    labs(title = "Cell composition distribution for each group with different clinical stages",
         x = "Clinical stage", y = "Cell proportion") +
    theme_classic()
  save_png(p_composition,
           file.path("figures", paste0(prefix, "_fig1E_cell_composition_matched_order.png")),
           width = 12, height = 6)

  # Recreate the earlier three-panel stage-split UMAP with the annotation's
  # original cell-type palette; keep identical UMAP coordinates in each panel.
  p_stage_split <- DimPlot(
    obj, reduction = "umap", group.by = "plot_cell_type_22",
    split.by = "clinical_stage_S1", cols = colors,
    pt.size = 0.18, raster = FALSE
  ) +
    labs(title = "Cell types across clinical stages", colour = "Cell type") +
    theme_classic() +
    theme(strip.text = element_text(face = "bold"))
  save_png(p_stage_split,
           file.path("figures", paste0(prefix, "_clinical_stage_split_UMAP.png")),
           width = 16, height = 6)

  # Figure 1E: all cells on their original global UMAP, coloured by stage.
  umap_xy <- as.data.frame(Embeddings(obj, reduction = "umap")[, 1:2, drop = FALSE])
  names(umap_xy) <- c("UMAP_1", "UMAP_2")
  umap_xy$clinical_stage <- obj$clinical_stage_S1
  p_1e <- ggplot(umap_xy, aes(x = UMAP_1, y = UMAP_2,
                               colour = clinical_stage)) +
    geom_point(size = 0.17, alpha = 0.75) +
    scale_colour_manual(values = stage_colors, breaks = stage_levels,
                        drop = FALSE, name = "Clinical stage") +
    coord_equal() +
    labs(title = "Cell composition distribution for each group with different clinical stages",
         x = "UMAP_1", y = "UMAP_2") +
    theme_classic()
  save_png(p_1e, file.path("figures", paste0(prefix, "_fig1E_contrast_stage_UMAP.png")),
           width = 9, height = 7)
  message(prefix, ": saved Fig. 1C dot plot, matched-order composition chart, ",
          "stage-split UMAP, Fig. 1E stage UMAP, and sample-stage mapping table.")
}

make_figures("results/02_integrated_seurat.rds", "02_Xu_annotation",
             "cell_type", original_colors)
make_figures("results/02.1_integrated_seurat_refined.rds", "02.1_refined_annotation",
             "cell_type_refined", refined_colors)
dir.create("results", showWarnings = FALSE, recursive = TRUE)
writeLines(
  capture.output(sessionInfo()),
  con = "results/02.2_session_info.txt"
)
